/*
 * Email Validator
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gofiber/fiber/v2"
)

// EmailValidationApiRouter defines the required methods for binding the api requests to a responses for the EmailValidationApi
// The EmailValidationApiRouter implementation should parse necessary information from the http request,
// pass the data to a EmailValidationApiServicer to perform the required actions, then write the service results to the http response.
type EmailValidationApiRouter interface {
	EmailValidationSingleValidationGet(c *fiber.Ctx) error
	EmailValidationSingleValidationPost(c *fiber.Ctx) error
}
