/*
 * Email Validator
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EmailRequest struct {
	Email string `json:"email,omitempty"`

	ResultType ResultType `json:"resultType,omitempty"`
}
