/*
 * Email Validator
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EmailResponse struct {
	Input string `json:"input,omitempty"`

	IsReachable string `json:"is_reachable,omitempty"`

	Misc CheckIfEmailExistMisc `json:"misc,omitempty"`

	Mx CheckIfEmailExistMx `json:"mx,omitempty"`

	Smtp CheckIfEmailExistSmtp `json:"smtp,omitempty"`

	Syntax CheckIfEmailExistSyntax `json:"syntax,omitempty"`

	Error string `json:"error,omitempty"`

	EmailAddress string `json:"email_address,omitempty"`

	Domain string `json:"domain,omitempty"`

	IsFree string `json:"is_free,omitempty"`

	IsSyntax string `json:"is_syntax,omitempty"`

	IsDomain string `json:"is_domain,omitempty"`

	IsSmtp string `json:"is_smtp,omitempty"`

	IsVerified string `json:"is_verified,omitempty"`

	IsServerDown string `json:"is_server_down,omitempty"`

	IsGreylisted string `json:"is_greylisted,omitempty"`

	IsDisposable bool `json:"is_disposable,omitempty"`

	IsSuppressed string `json:"is_suppressed,omitempty"`

	IsRole string `json:"is_role,omitempty"`

	IsHighRisk string `json:"is_high_risk,omitempty"`

	IsCatchall string `json:"is_catchall,omitempty"`

	MailboxvalidatorScore string `json:"mailboxvalidator_score,omitempty"`

	TimeTaken string `json:"time_taken,omitempty"`

	Status string `json:"status,omitempty"`

	CreditsAvailable int64 `json:"credits_available,omitempty"`

	ErrorCode string `json:"error_code,omitempty"`

	ErrorMessage string `json:"error_message,omitempty"`

	CanConnectSmtp bool `json:"can_connect_smtp,omitempty"`

	Email string `json:"email,omitempty"`

	IsCatchAll bool `json:"is_catch_all,omitempty"`

	IsDeliverable bool `json:"is_deliverable,omitempty"`

	IsDisabled bool `json:"is_disabled,omitempty"`

	IsInboxFull bool `json:"is_inbox_full,omitempty"`

	IsRoleAccount bool `json:"is_role_account,omitempty"`

	MxRecords PromptEmailVerificationApiMx `json:"mx_records,omitempty"`

	SyntaxValid bool `json:"syntax_valid,omitempty"`

	Message string `json:"message,omitempty"`
}
