/*
 * Email Validator
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CheckIfEmailExistSyntax struct {
	Address string `json:"address,omitempty"`

	Domain string `json:"domain,omitempty"`

	IsValidSyntax bool `json:"is_valid_syntax,omitempty"`

	Username string `json:"username,omitempty"`
}
