/*
 * Email Validator
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EmailRequestGravatar struct {

	// timeout request to gravatar.com
	Timeout float32 `json:"timeout,omitempty"`
}
