/*
 * Email Validator
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UnexpectedError struct {
	Code int32 `json:"code,omitempty"`

	Message string `json:"message,omitempty"`

	Details map[string]map[string]interface{} `json:"details,omitempty"`
}
