/*
 * Email Validator
 *
 * All timeouts are set in seconds with nanosecond precision. For example, 1.505402 is 1 second, 505 milliseconds and 402 microseconds.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UnexpectedError struct {
	Code int32 `json:"code,omitempty"`

	Message string `json:"message,omitempty"`

	Details map[string]map[string]interface{} `json:"details,omitempty"`
}
