/*
 * Email Validator
 *
 * All timeouts are set in seconds with nanosecond precision. For example, 1.505402 is 1 second, 505 milliseconds and 402 microseconds.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EmailRequest struct {
	Email string `json:"email,omitempty"`

	Smtp EmailRequestSmtp `json:"smtp,omitempty"`

	ResultType ResultType `json:"result_type,omitempty"`
}
