/*
 * Email Validator
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EmailRequestSmtp struct {
	EmailFrom string `json:"email_from,omitempty"`

	HelloName string `json:"hello_name,omitempty"`

	// socks proxy in format schema://username:password@host:port
	Proxy string `json:"proxy,omitempty"`

	// timeout creating smtp connection
	TimeoutConnection float32 `json:"timeout_connection,omitempty"`

	// timeout of communication with smtp server
	TimeoutResponse float32 `json:"timeout_response,omitempty"`

	// smtp port remote server
	Port int64 `json:"port,omitempty"`
}
