/*
 * Email Validator
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CheckIfEmailExistMisc struct {
	IsDisposable bool `json:"is_disposable,omitempty"`

	IsRoleAccount bool `json:"is_role_account,omitempty"`
}
