/*
 * Email Validator
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CheckIfEmailExistSmtp struct {
	CanConnectSmtp bool `json:"can_connect_smtp,omitempty"`

	HasFullInbox bool `json:"has_full_inbox,omitempty"`

	IsCatchAll bool `json:"is_catch_all,omitempty"`

	IsDeliverable bool `json:"is_deliverable,omitempty"`

	IsDisabled bool `json:"is_disabled,omitempty"`
}
