/*
 * Email Validator
 *
 * All timeouts are set in seconds with nanosecond precision. For example, 1.505402 is 1 second, 505 milliseconds and 402 microseconds.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EmailRequestSmtp struct {
	EmailFrom string `json:"email_from,omitempty"`

	HelloName string `json:"hello_name,omitempty"`

	// Versions - SOCKS4, SOCKS4A and SOCKS5. Format -  schema://username:password@host:port.
	Proxy string `json:"proxy,omitempty"`

	// timeout creating smtp connection
	TimeoutConnection float32 `json:"timeout_connection,omitempty"`

	// timeout of communication with smtp server
	TimeoutResponse float32 `json:"timeout_response,omitempty"`

	// smtp port remote server
	Port int32 `json:"port,omitempty"`
}
