/*
 * Email Validator
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CheckIfEmailExistMx struct {
	AcceptsMail bool `json:"accepts_mail,omitempty"`

	Records []string `json:"records,omitempty"`
}
