/*
 * Email Validator
 *
 * All timeouts are set in seconds with nanosecond precision. For example, 1.505402 is 1 second, 505 milliseconds and 402 microseconds.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EmailResponse struct {
	CheckIfEmailExist CheckIfEmailExistResult `json:"check_if_email_exist,omitempty"`

	Mailboxvalidator MailboxvalidatorResult `json:"mailboxvalidator,omitempty"`

	PromptEmailVerificationApi PromptEmailVerificationApiResult `json:"prompt_email_verification_api,omitempty"`
}
