// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ev.proto

package v1

import (
	context "context"
	fmt "fmt"
	check_if_email_exist "github.com/go-email-validator/go-ev-presenters/pkg/api/v1/check_if_email_exist"
	mailboxvalidator "github.com/go-email-validator/go-ev-presenters/pkg/api/v1/mailboxvalidator"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ResultType int32

const (
	ResultType_CHECK_IF_EMAIL_EXIST ResultType = 0
	ResultType_CIEE                 ResultType = 0
	ResultType_MAILBOXVALIDATOR     ResultType = 1
	ResultType_MAIL_BOX_VALIDATOR   ResultType = 1
	ResultType_MBV                  ResultType = 1
)

var ResultType_name = map[int32]string{
	0: "CHECK_IF_EMAIL_EXIST",
	// Duplicate value: 0: "CIEE",
	1: "MAILBOXVALIDATOR",
	// Duplicate value: 1: "MAIL_BOX_VALIDATOR",
	// Duplicate value: 1: "MBV",
}

var ResultType_value = map[string]int32{
	"CHECK_IF_EMAIL_EXIST": 0,
	"CIEE":                 0,
	"MAILBOXVALIDATOR":     1,
	"MAIL_BOX_VALIDATOR":   1,
	"MBV":                  1,
}

func (x ResultType) String() string {
	return proto.EnumName(ResultType_name, int32(x))
}

func (ResultType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9dd0443f2ac7fc36, []int{0}
}

type EmailRequest struct {
	Email                string     `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	ResultType           ResultType `protobuf:"varint,2,opt,name=result_type,json=resultType,proto3,enum=github.com.go_email_validator.go_ev_presenters.api.v1.ResultType" json:"result_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EmailRequest) Reset()         { *m = EmailRequest{} }
func (m *EmailRequest) String() string { return proto.CompactTextString(m) }
func (*EmailRequest) ProtoMessage()    {}
func (*EmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9dd0443f2ac7fc36, []int{0}
}
func (m *EmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailRequest.Unmarshal(m, b)
}
func (m *EmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailRequest.Marshal(b, m, deterministic)
}
func (m *EmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailRequest.Merge(m, src)
}
func (m *EmailRequest) XXX_Size() int {
	return xxx_messageInfo_EmailRequest.Size(m)
}
func (m *EmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmailRequest proto.InternalMessageInfo

func (m *EmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *EmailRequest) GetResultType() ResultType {
	if m != nil {
		return m.ResultType
	}
	return ResultType_CHECK_IF_EMAIL_EXIST
}

type EmailResponse struct {
	// Types that are valid to be assigned to Result:
	//	*EmailResponse_CheckIfEmailExist
	//	*EmailResponse_MailBoxValidator
	Result               IsEmailResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *EmailResponse) Reset()         { *m = EmailResponse{} }
func (m *EmailResponse) String() string { return proto.CompactTextString(m) }
func (*EmailResponse) ProtoMessage()    {}
func (*EmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9dd0443f2ac7fc36, []int{1}
}
func (m *EmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailResponse.Unmarshal(m, b)
}
func (m *EmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailResponse.Marshal(b, m, deterministic)
}
func (m *EmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailResponse.Merge(m, src)
}
func (m *EmailResponse) XXX_Size() int {
	return xxx_messageInfo_EmailResponse.Size(m)
}
func (m *EmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmailResponse proto.InternalMessageInfo

type IsEmailResponse_Result interface {
	isEmailResponse_Result()
}

type EmailResponse_CheckIfEmailExist struct {
	CheckIfEmailExist *check_if_email_exist.Result `protobuf:"bytes,1,opt,name=check_if_email_exist,json=checkIfEmailExist,proto3,oneof" json:"check_if_email_exist,omitempty"`
}
type EmailResponse_MailBoxValidator struct {
	MailBoxValidator *mailboxvalidator.Result `protobuf:"bytes,2,opt,name=mail_box_validator,json=mailBoxValidator,proto3,oneof" json:"mail_box_validator,omitempty"`
}

func (*EmailResponse_CheckIfEmailExist) isEmailResponse_Result() {}
func (*EmailResponse_MailBoxValidator) isEmailResponse_Result()  {}

func (m *EmailResponse) GetResult() IsEmailResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *EmailResponse) GetCheckIfEmailExist() *check_if_email_exist.Result {
	if x, ok := m.GetResult().(*EmailResponse_CheckIfEmailExist); ok {
		return x.CheckIfEmailExist
	}
	return nil
}

func (m *EmailResponse) GetMailBoxValidator() *mailboxvalidator.Result {
	if x, ok := m.GetResult().(*EmailResponse_MailBoxValidator); ok {
		return x.MailBoxValidator
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*EmailResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*EmailResponse_CheckIfEmailExist)(nil),
		(*EmailResponse_MailBoxValidator)(nil),
	}
}

func init() {
	proto.RegisterEnum("github.com.go_email_validator.go_ev_presenters.api.v1.ResultType", ResultType_name, ResultType_value)
	proto.RegisterType((*EmailRequest)(nil), "github.com.go_email_validator.go_ev_presenters.api.v1.EmailRequest")
	proto.RegisterType((*EmailResponse)(nil), "github.com.go_email_validator.go_ev_presenters.api.v1.EmailResponse")
}

func init() { proto.RegisterFile("ev.proto", fileDescriptor_9dd0443f2ac7fc36) }

var fileDescriptor_9dd0443f2ac7fc36 = []byte{
	// 440 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xcd, 0x06, 0x28, 0x61, 0xc2, 0xc7, 0xb2, 0x8a, 0x50, 0x94, 0x53, 0x95, 0x53, 0x85, 0x94,
	0xb5, 0x1a, 0xc4, 0x01, 0x71, 0x8a, 0x53, 0xa3, 0x5a, 0xb4, 0x8a, 0x64, 0xa2, 0x28, 0x2a, 0x87,
	0x95, 0x1d, 0xb6, 0xee, 0x2a, 0xa9, 0x77, 0xf1, 0x6e, 0x2c, 0xf7, 0x0f, 0x20, 0x2e, 0xfc, 0x06,
	0xfe, 0x03, 0xfc, 0x41, 0xe4, 0xb5, 0xa9, 0x2d, 0x94, 0x0b, 0xc9, 0xcd, 0x33, 0x6f, 0xde, 0xbc,
	0xa7, 0xe7, 0x59, 0xe8, 0xf0, 0x8c, 0xaa, 0x54, 0x1a, 0x49, 0xde, 0xc6, 0xc2, 0xdc, 0x6c, 0x23,
	0xba, 0x92, 0xb7, 0x34, 0x96, 0x8c, 0xdf, 0x86, 0x62, 0xc3, 0xb2, 0x70, 0x23, 0xbe, 0x84, 0x46,
	0xa6, 0xb6, 0x95, 0x31, 0x95, 0x72, 0xcd, 0x13, 0xc3, 0x53, 0x4d, 0x43, 0x25, 0x68, 0x76, 0x3a,
	0x60, 0x35, 0xcd, 0x89, 0xe5, 0xc8, 0xd2, 0x46, 0xf7, 0x34, 0xdb, 0xca, 0x46, 0x35, 0xcd, 0x51,
	0xeb, 0xd8, 0x69, 0x94, 0xab, 0x1b, 0xbe, 0x5a, 0x33, 0x71, 0x5d, 0xe9, 0xf1, 0x5c, 0x68, 0xe3,
	0xa4, 0x5c, 0x6f, 0x37, 0xa6, 0xf4, 0x35, 0xf8, 0x7c, 0x98, 0x40, 0x31, 0x1e, 0xc9, 0xbc, 0x26,
	0x34, 0x97, 0x0f, 0xbf, 0x23, 0x78, 0xea, 0x15, 0x23, 0x01, 0xff, 0xba, 0xe5, 0xda, 0x90, 0x1e,
	0x3c, 0xb2, 0x0a, 0x7d, 0x74, 0x8c, 0x4e, 0x9e, 0x04, 0x65, 0x41, 0x22, 0xe8, 0x96, 0x34, 0x66,
	0xee, 0x14, 0xef, 0xb7, 0x8f, 0xd1, 0xc9, 0xf3, 0xf1, 0x84, 0xee, 0x95, 0x18, 0x0d, 0xec, 0xa6,
	0xf9, 0x9d, 0xe2, 0x01, 0xa4, 0xf7, 0xdf, 0xc3, 0x5f, 0x6d, 0x78, 0x56, 0x59, 0xd1, 0x4a, 0x26,
	0x9a, 0x93, 0x1f, 0x08, 0x7a, 0xbb, 0xf2, 0xb1, 0xde, 0xba, 0xe3, 0xab, 0xff, 0xd5, 0x57, 0xeb,
	0x98, 0x36, 0xca, 0x5d, 0xab, 0x2b, 0x73, 0xe7, 0xad, 0xe0, 0xa5, 0x85, 0xfd, 0x6b, 0x6b, 0xc9,
	0x2b, 0x30, 0xf2, 0x0d, 0x01, 0xb1, 0xa3, 0x91, 0xcc, 0x6b, 0x1d, 0x9b, 0x46, 0x77, 0xbc, 0x38,
	0xd0, 0xcd, 0xbf, 0xff, 0xa9, 0x76, 0x82, 0x0b, 0xc8, 0x95, 0xf9, 0xe2, 0x2f, 0xe4, 0x76, 0xe0,
	0xa8, 0x0c, 0xee, 0xf5, 0x1a, 0xa0, 0x8e, 0x93, 0xf4, 0xa1, 0x37, 0x3d, 0xf7, 0xa6, 0x1f, 0x99,
	0xff, 0x81, 0x79, 0x97, 0x13, 0xff, 0x82, 0x79, 0x4b, 0xff, 0xd3, 0x1c, 0xb7, 0x48, 0x07, 0x1e,
	0x4e, 0x7d, 0xcf, 0xc3, 0x2d, 0xd2, 0x03, 0x5c, 0x20, 0xee, 0x6c, 0xb9, 0x98, 0x5c, 0xf8, 0x67,
	0x93, 0xf9, 0x2c, 0xc0, 0x88, 0xbc, 0x02, 0x62, 0xe7, 0xdd, 0xd9, 0x92, 0x35, 0xfb, 0x8f, 0xe1,
	0xc1, 0xa5, 0xbb, 0xc0, 0x68, 0xd0, 0xc6, 0x68, 0xfc, 0x1b, 0xc1, 0x0b, 0x1b, 0x47, 0xe5, 0x44,
	0xc8, 0x84, 0xfc, 0x44, 0x80, 0xb5, 0x48, 0xe2, 0x0d, 0x6f, 0x34, 0xa7, 0x7b, 0x5e, 0x46, 0xf3,
	0x12, 0x07, 0x67, 0x87, 0x2d, 0x29, 0x6f, 0x68, 0xd8, 0x72, 0xdf, 0x5f, 0xbd, 0xdb, 0xe3, 0x05,
	0x85, 0x4a, 0x38, 0xd9, 0x69, 0x74, 0x64, 0x9f, 0xc9, 0x9b, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x99, 0xbf, 0x60, 0xaa, 0x27, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmailValidationClient is the client API for EmailValidation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmailValidationClient interface {
	SingleValidation(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailResponse, error)
}

type emailValidationClient struct {
	cc *grpc.ClientConn
}

func NewEmailValidationClient(cc *grpc.ClientConn) EmailValidationClient {
	return &emailValidationClient{cc}
}

func (c *emailValidationClient) SingleValidation(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailResponse, error) {
	out := new(EmailResponse)
	err := c.cc.Invoke(ctx, "/github.com.go_email_validator.go_ev_presenters.api.v1.EmailValidation/singleValidation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailValidationServer is the server API for EmailValidation service.
type EmailValidationServer interface {
	SingleValidation(context.Context, *EmailRequest) (*EmailResponse, error)
}

// UnimplementedEmailValidationServer can be embedded to have forward compatible implementations.
type UnimplementedEmailValidationServer struct {
}

func (*UnimplementedEmailValidationServer) SingleValidation(ctx context.Context, req *EmailRequest) (*EmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SingleValidation not implemented")
}

func RegisterEmailValidationServer(s *grpc.Server, srv EmailValidationServer) {
	s.RegisterService(&_EmailValidation_serviceDesc, srv)
}

func _EmailValidation_SingleValidation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailValidationServer).SingleValidation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.go_email_validator.go_ev_presenters.api.v1.EmailValidation/SingleValidation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailValidationServer).SingleValidation(ctx, req.(*EmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EmailValidation_serviceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.go_email_validator.go_ev_presenters.api.v1.EmailValidation",
	HandlerType: (*EmailValidationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "singleValidation",
			Handler:    _EmailValidation_SingleValidation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ev.proto",
}
