package mailboxvalidator

import (
	"math"
	"testing"
	"time"
)

func TestCalculateScore(t *testing.T) {
	tests := []DepPresenter{
		{
			EmailAddress:          "asdas.da2da",
			Domain:                "asdas.da2da",
			IsFree:                false,
			IsSyntax:              false,
			IsDomain:              false,
			IsSmtp:                false,
			IsVerified:            false,
			IsServerDown:          false,
			IsGreylisted:          false,
			IsDisposable:          false,
			IsSuppressed:          false,
			IsRole:                false,
			IsHighRisk:            false,
			IsCatchall:            false,
			MailboxvalidatorScore: 0.0,
			TimeTaken:             time.Duration(math.RoundToEven(0.5811*1000000)) * time.Microsecond,
			Status:                false,
		},
		{
			EmailAddress:          "asdas.dada",
			Domain:                "asdas.dada",
			IsFree:                false,
			IsSyntax:              false,
			IsDomain:              false,
			IsSmtp:                false,
			IsVerified:            false,
			IsServerDown:          false,
			IsGreylisted:          false,
			IsDisposable:          false,
			IsSuppressed:          false,
			IsRole:                false,
			IsHighRisk:            false,
			IsCatchall:            false,
			MailboxvalidatorScore: 0.02,
			TimeTaken:             time.Duration(math.RoundToEven(0.0225*1000000)) * time.Microsecond,
			Status:                false,
		},

		{
			EmailAddress:          "asd@asd@asd",
			Domain:                "asd",
			IsFree:                false,
			IsSyntax:              false,
			IsDomain:              false,
			IsSmtp:                false,
			IsVerified:            false,
			IsServerDown:          false,
			IsGreylisted:          false,
			IsDisposable:          false,
			IsSuppressed:          false,
			IsRole:                false,
			IsHighRisk:            false,
			IsCatchall:            false,
			MailboxvalidatorScore: 0.01,
			TimeTaken:             time.Duration(math.RoundToEven(0.296*1000000)) * time.Microsecond,
			Status:                false,
		},

		{
			EmailAddress:          "zxczxczxc@joycasinoru",
			Domain:                "joycasinoru",
			IsFree:                false,
			IsSyntax:              true,
			IsDomain:              true,
			IsSmtp:                false,
			IsVerified:            false,
			IsServerDown:          false,
			IsGreylisted:          false,
			IsDisposable:          false,
			IsSuppressed:          false,
			IsRole:                false,
			IsHighRisk:            false,
			IsCatchall:            false,
			MailboxvalidatorScore: 0.1,
			TimeTaken:             time.Duration(math.RoundToEven(0.5683*1000000)) * time.Microsecond,
			Status:                false,
		},

		{
			EmailAddress:          "sewag33689@gmail.com",
			Domain:                "gmail.com",
			IsFree:                true,
			IsSyntax:              true,
			IsDomain:              true,
			IsSmtp:                true,
			IsVerified:            false,
			IsServerDown:          false,
			IsGreylisted:          false,
			IsDisposable:          false,
			IsSuppressed:          false,
			IsRole:                false,
			IsHighRisk:            false,
			IsCatchall:            false,
			MailboxvalidatorScore: 0.18,
			TimeTaken:             time.Duration(math.RoundToEven(0.035*1000000)) * time.Microsecond,
			Status:                false,
		},
		{
			EmailAddress:          "user99.doesnot.exist@gmail.com",
			Domain:                "gmail.com",
			IsFree:                true,
			IsSyntax:              true,
			IsDomain:              true,
			IsSmtp:                true,
			IsVerified:            false,
			IsServerDown:          false,
			IsGreylisted:          false,
			IsDisposable:          false,
			IsSuppressed:          false,
			IsRole:                false,
			IsHighRisk:            false,
			IsCatchall:            false,
			MailboxvalidatorScore: 0.19,
			TimeTaken:             time.Duration(math.RoundToEven(0.5767*1000000)) * time.Microsecond,
			Status:                false,
		},
		{
			EmailAddress:          "amazedfuckporno@gmail.com",
			Domain:                "gmail.com",
			IsFree:                true,
			IsSyntax:              true,
			IsDomain:              true,
			IsSmtp:                true,
			IsVerified:            false,
			IsServerDown:          false,
			IsGreylisted:          false,
			IsDisposable:          false,
			IsSuppressed:          false,
			IsRole:                false,
			IsHighRisk:            false,
			IsCatchall:            false,
			MailboxvalidatorScore: 0.2,
			TimeTaken:             time.Duration(math.RoundToEven(0.497*1000000)) * time.Microsecond,
			Status:                false,
		},

		{
			EmailAddress:          "sewag33689@itymail.com",
			Domain:                "itymail.com",
			IsFree:                false,
			IsSyntax:              true,
			IsDomain:              true,
			IsSmtp:                true,
			IsVerified:            true,
			IsServerDown:          false,
			IsGreylisted:          false,
			IsDisposable:          true,
			IsSuppressed:          false,
			IsRole:                false,
			IsHighRisk:            false,
			IsCatchall:            true,
			MailboxvalidatorScore: 0.23,
			TimeTaken:             time.Duration(math.RoundToEven(0.0247*1000000)) * time.Microsecond,
			Status:                false,
		},
		{
			EmailAddress:          "derduzikne@nedoz.com",
			Domain:                "nedoz.com",
			IsFree:                false,
			IsSyntax:              true,
			IsDomain:              true,
			IsSmtp:                true,
			IsVerified:            true,
			IsServerDown:          false,
			IsGreylisted:          false,
			IsDisposable:          true,
			IsSuppressed:          false,
			IsRole:                false,
			IsHighRisk:            false,
			IsCatchall:            true,
			MailboxvalidatorScore: 0.25,
			TimeTaken:             time.Duration(math.RoundToEven(0.0986*1000000)) * time.Microsecond,
			Status:                false,
		},
		{
			EmailAddress:          "tvzamhkdc@emlhub.com",
			Domain:                "emlhub.com",
			IsFree:                false,
			IsSyntax:              true,
			IsDomain:              true,
			IsSmtp:                true,
			IsVerified:            true,
			IsServerDown:          false,
			IsGreylisted:          false,
			IsDisposable:          true,
			IsSuppressed:          false,
			IsRole:                false,
			IsHighRisk:            false,
			IsCatchall:            false,
			MailboxvalidatorScore: 0.3,
			TimeTaken:             time.Duration(math.RoundToEven(0.0226*1000000)) * time.Microsecond,
			Status:                false,
		},
		{
			EmailAddress:          "theofanis.giot2is@12pm.gr",
			Domain:                "12pm.gr",
			IsFree:                false,
			IsSyntax:              true,
			IsDomain:              true,
			IsSmtp:                true,
			IsVerified:            true,
			IsServerDown:          false,
			IsGreylisted:          false,
			IsDisposable:          false,
			IsSuppressed:          false,
			IsRole:                false,
			IsHighRisk:            false,
			IsCatchall:            true,
			MailboxvalidatorScore: 0.54,
			TimeTaken:             time.Duration(math.RoundToEven(1.5016*1000000)) * time.Microsecond,
			Status:                true,
		},
		{
			EmailAddress:          "theofanisgiotis@12pm.gr",
			Domain:                "12pm.gr",
			IsFree:                false,
			IsSyntax:              true,
			IsDomain:              true,
			IsSmtp:                true,
			IsVerified:            true,
			IsServerDown:          false,
			IsGreylisted:          false,
			IsDisposable:          false,
			IsSuppressed:          false,
			IsRole:                false,
			IsHighRisk:            false,
			IsCatchall:            true,
			MailboxvalidatorScore: 0.55,
			TimeTaken:             time.Duration(math.RoundToEven(1.6909*1000000)) * time.Microsecond,
			Status:                true,
		},
		{
			EmailAddress:          "asdasd@tradepro.net",
			Domain:                "tradepro.net",
			IsFree:                false,
			IsSyntax:              true,
			IsDomain:              true,
			IsSmtp:                true,
			IsVerified:            true,
			IsServerDown:          false,
			IsGreylisted:          false,
			IsDisposable:          false,
			IsSuppressed:          false,
			IsRole:                false,
			IsHighRisk:            false,
			IsCatchall:            true,
			MailboxvalidatorScore: 0.55,
			TimeTaken:             time.Duration(math.RoundToEven(1.2939*1000000)) * time.Microsecond,
			Status:                true,
		},
		{
			EmailAddress:          "credit@mail.ru",
			Domain:                "mail.ru",
			IsFree:                true,
			IsSyntax:              true,
			IsDomain:              true,
			IsSmtp:                true,
			IsVerified:            true,
			IsServerDown:          false,
			IsGreylisted:          false,
			IsDisposable:          false,
			IsSuppressed:          false,
			IsRole:                false,
			IsHighRisk:            false,
			IsCatchall:            true,
			MailboxvalidatorScore: 0.55,
			TimeTaken:             time.Duration(math.RoundToEven(1.1038*1000000)) * time.Microsecond,
			Status:                true,
		},
		{
			EmailAddress:          "salestrade86@hotmail.com",
			Domain:                "hotmail.com",
			IsFree:                true,
			IsSyntax:              true,
			IsDomain:              true,
			IsSmtp:                true,
			IsVerified:            true,
			IsServerDown:          false,
			IsGreylisted:          false,
			IsDisposable:          false,
			IsSuppressed:          false,
			IsRole:                false,
			IsHighRisk:            false,
			IsCatchall:            false,
			MailboxvalidatorScore: 0.58,
			TimeTaken:             time.Duration(math.RoundToEven(0.0811*1000000)) * time.Microsecond,
			Status:                true,
		},
		{
			EmailAddress:          "some.user.99@gmail.com",
			Domain:                "gmail.com",
			IsFree:                true,
			IsSyntax:              true,
			IsDomain:              true,
			IsSmtp:                true,
			IsVerified:            true,
			IsServerDown:          false,
			IsGreylisted:          false,
			IsDisposable:          false,
			IsSuppressed:          false,
			IsRole:                false,
			IsHighRisk:            false,
			IsCatchall:            false,
			MailboxvalidatorScore: 0.59,
			TimeTaken:             time.Duration(math.RoundToEven(0.1024*1000000)) * time.Microsecond,
			Status:                true,
		},
		{
			EmailAddress:          "monicaramirezrestrepo@hotmail.com",
			Domain:                "hotmail.com",
			IsFree:                true,
			IsSyntax:              true,
			IsDomain:              true,
			IsSmtp:                true,
			IsVerified:            true,
			IsServerDown:          false,
			IsGreylisted:          false,
			IsDisposable:          false,
			IsSuppressed:          false,
			IsRole:                false,
			IsHighRisk:            false,
			IsCatchall:            false,
			MailboxvalidatorScore: 0.6,
			TimeTaken:             time.Duration(math.RoundToEven(0.0319*1000000)) * time.Microsecond,
			Status:                true,
		},
		{
			EmailAddress:          "admin@gmail.com",
			Domain:                "gmail.com",
			IsFree:                true,
			IsSyntax:              true,
			IsDomain:              true,
			IsSmtp:                true,
			IsVerified:            true,
			IsServerDown:          false,
			IsGreylisted:          false,
			IsDisposable:          false,
			IsSuppressed:          false,
			IsRole:                true,
			IsHighRisk:            false,
			IsCatchall:            false,
			MailboxvalidatorScore: 0.6,
			TimeTaken:             time.Duration(math.RoundToEven(0.0579*1000000)) * time.Microsecond,
			Status:                true,
		},
		{
			EmailAddress:          "name@yandex.ru",
			Domain:                "yandex.ru",
			IsFree:                true,
			IsSyntax:              true,
			IsDomain:              true,
			IsSmtp:                true,
			IsVerified:            true,
			IsServerDown:          false,
			IsGreylisted:          false,
			IsDisposable:          false,
			IsSuppressed:          false,
			IsRole:                false,
			IsHighRisk:            false,
			IsCatchall:            false,
			MailboxvalidatorScore: 0.6,
			TimeTaken:             time.Duration(math.RoundToEven(0.023*1000000)) * time.Microsecond,
			Status:                true,
		},
		{
			EmailAddress:          "admin@huntgear.ru",
			Domain:                "huntgear.ru",
			IsFree:                false,
			IsSyntax:              true,
			IsDomain:              true,
			IsSmtp:                true,
			IsVerified:            true,
			IsServerDown:          false,
			IsGreylisted:          false,
			IsDisposable:          false,
			IsSuppressed:          false,
			IsRole:                true,
			IsHighRisk:            false,
			IsCatchall:            false,
			MailboxvalidatorScore: 0.6,
			TimeTaken:             time.Duration(math.RoundToEven(4.3725*1000000)) * time.Microsecond,
			Status:                true,
		},
		{
			EmailAddress:          "go.email.validator@gmail.com",
			Domain:                "gmail.com",
			IsFree:                true,
			IsSyntax:              true,
			IsDomain:              true,
			IsSmtp:                true,
			IsVerified:            true,
			IsServerDown:          false,
			IsGreylisted:          false,
			IsDisposable:          false,
			IsSuppressed:          false,
			IsRole:                false,
			IsHighRisk:            false,
			IsCatchall:            false,
			MailboxvalidatorScore: 0.61,
			TimeTaken:             time.Duration(math.RoundToEven(0.7789*1000000)) * time.Microsecond,
			Status:                true,
		},
		{
			EmailAddress:          "radmal1982@yandex-team.ru",
			Domain:                "yandex-team.ru",
			IsFree:                false,
			IsSyntax:              true,
			IsDomain:              true,
			IsSmtp:                true,
			IsVerified:            true,
			IsServerDown:          false,
			IsGreylisted:          false,
			IsDisposable:          false,
			IsSuppressed:          false,
			IsRole:                false,
			IsHighRisk:            false,
			IsCatchall:            false,
			MailboxvalidatorScore: 0.97,
			TimeTaken:             time.Duration(math.RoundToEven(1.2021*1000000)) * time.Microsecond,
			Status:                true,
		},
		{
			EmailAddress:          "pr@yandex-team.ru",
			Domain:                "yandex-team.ru",
			IsFree:                false,
			IsSyntax:              true,
			IsDomain:              true,
			IsSmtp:                true,
			IsVerified:            true,
			IsServerDown:          false,
			IsGreylisted:          false,
			IsDisposable:          false,
			IsSuppressed:          false,
			IsRole:                false,
			IsHighRisk:            false,
			IsCatchall:            false,
			MailboxvalidatorScore: 0.99,
			TimeTaken:             time.Duration(math.RoundToEven(2.0969*1000000)) * time.Microsecond,
			Status:                true,
		},
		{
			EmailAddress:          "y-numata@senko.ed.jp",
			Domain:                "senko.ed.jp",
			IsFree:                false,
			IsSyntax:              true,
			IsDomain:              true,
			IsSmtp:                true,
			IsVerified:            true,
			IsServerDown:          false,
			IsGreylisted:          false,
			IsDisposable:          false,
			IsSuppressed:          false,
			IsRole:                false,
			IsHighRisk:            false,
			IsCatchall:            false,
			MailboxvalidatorScore: 0.99,
			TimeTaken:             time.Duration(math.RoundToEven(2.7663*1000000)) * time.Microsecond,
			Status:                true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.EmailAddress, func(t *testing.T) {
			if got := CalculateScore(tt); got != tt.MailboxvalidatorScore {
				t.Errorf("CalculateScore() = %v, want %v", got, tt.MailboxvalidatorScore)
			}
		})
	}
}
