openapi: 3.0.3
info:
  title: EmailValidation
  version: 0.0.1
paths:
  /v1/validation/single:
    post:
      operationId: EmailValidation_SingleValidation_Post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailRequest'
        required: true
      responses:
        "200":
          $ref: '#/components/responses/EmailResponse200'
    get:
      operationId: EmailValidation_SingleValidation_Get
      parameters:
        - name: email
          in: path
          required: true
          schema:
            type: string
            format: email
        - name: result_type
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/ResultType'
      responses:
        "200":
          $ref: '#/components/responses/EmailResponse200'
components:
  schemas:
    ResultType:
      type: integer
      enum:
        - 0 # CHECK_IF_EMAIL_EXIST
        - 1 # MAIL_BOX_VALIDATOR
    EmailRequest:
      properties:
        email:
          type: string
        result_type:
          $ref: '#/components/schemas/EmailResponse'
    EmailResponse:
      properties:
        check_if_email_exist:
          $ref: '#/components/schemas/CheckIfEmailExist'
        mail_box_validator:
          $ref: '#/components/schemas/MailBoxValidator'
    MX:
      properties:
        accepts_mail:
          type: boolean
        records:
          type: array
          items:
            type: string
    Misc:
      properties:
        is_disposable:
          type: boolean
        is_role_account:
          type: boolean
    CheckIfEmailExist:
      properties:
        input:
          type: string
        is_reachable:
          type: string
        misc:
          $ref: '#/components/schemas/Misc'
        mx:
          $ref: '#/components/schemas/MX'
        smtp:
          $ref: '#/components/schemas/SMTP'
        syntax:
          $ref: '#/components/schemas/Syntax'
    MailBoxValidator:
      properties:
        email_address:
          type: string
        domain:
          type: string
        is_free:
          type: string
        is_syntax:
          type: string
        is_domain:
          type: string
        is_smtp:
          type: string
        is_verified:
          type: string
        is_server_down:
          type: string
        is_greylisted:
          type: string
        is_disposable:
          type: string
        is_suppressed:
          type: string
        is_role:
          type: string
        is_high_risk:
          type: string
        is_catchall:
          type: string
        mailboxvalidator_score:
          type: string
        time_taken:
          type: string
        status:
          type: string
        credits_available:
          type: integer
          format: uint32
        error_code:
          type: string
        error_message:
          type: string
    SMTP:
      properties:
        can_connect_smtp:
          type: boolean
        has_full_inbox:
          type: boolean
        is_catch_all:
          type: boolean
        is_deliverable:
          type: boolean
        is_disabled:
          type: boolean
    Syntax:
      properties:
        username:
          type: string
        domain:
          type: string
        is_valid_syntax:
          type: boolean
  responses:
    EmailResponse200:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EmailResponse'
