/*
 * Email Validator
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CheckIfEmailExistMisc struct {
	IsDisposable bool `json:"is_disposable,omitempty"`

	IsRoleAccount bool `json:"is_role_account,omitempty"`
}
