/*
 * Email Validator
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CheckIfEmailExistSmtp struct {
	CanConnectSmtp bool `json:"can_connect_smtp,omitempty"`

	HasFullInbox bool `json:"has_full_inbox,omitempty"`

	IsCatchAll bool `json:"is_catch_all,omitempty"`

	IsDeliverable bool `json:"is_deliverable,omitempty"`

	IsDisabled bool `json:"is_disabled,omitempty"`
}
