/*
 * Email Validator
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UnexpectedError struct {
	Code int32 `json:"code,omitempty"`

	Message string `json:"message,omitempty"`

	Details map[string]map[string]interface{} `json:"details,omitempty"`
}
