/*
 * Email Validator
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CheckIfEmailExistMx struct {
	AcceptsMail bool `json:"accepts_mail,omitempty"`

	Records []string `json:"records,omitempty"`
}
